### ISSUE TITLE
Fetch All Active Certificates option returns an error message pertaining revoked certs

### ISSUE THREAD

**Issue by pchithapuram1** [EntrustCorporation/pki-utilities#2]
When use the option 8 to fetch all active certificates from PKIaaS based Issuing CA, I get division by zero error message
![fetch_all_active_certs_error](https://github.com/EntrustCorporation/pki-utilities/assets/163223235/5c9da089-df99-4a1c-985d-570eaa3269f5)

**Comment by WantTrueNerds** [comment]
@pchithapuram1  - can you confirm if this occurred with the v1.0.0 release of the script?
I'm aware that this issue existed, but I thought it was fixed.
Please confirm if this issue still exists on the latest version: https://github.com/EntrustCorporation/pki-utilities/releases/tag/v1.0.0

**Comment by pchithapuram1** [comment]
@andrew-entrust - I downloaded the shell script right after the presentation session we had on Monday. Anyways, I downloaded the version from the link you provided and it seems to have fixed the active certificates report request. Btw, the legacy flag issue is still there with this version. Just FYI.

**Comment by WantTrueNerds** [comment]
Right, the fix for the legacy flag has only been fixed on the main branch of code. No release put out for that yet.

Just download the latest code from here for both fixes: https://raw.githubusercontent.com/EntrustCorporation/pki-utilities/main/cagw-shell-util/main.sh

**Comment by WantTrueNerds** [comment]
Closing this issue because it has already been fixed.
